export const data = [
    {
        s0: "Dung lượng lưu trữ",
        s1: "2 Gb/User",
        s2: "2 Gb/User",
        s3: "4 Gb/User",
        s4: "4 Gb/User",
    },
    {
        s0: "Gọi trực tiếp qua IP Phone",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
    {
        s0: "Gọi trực tiếp qua IP Phone",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
    {
        s0: "Gọi qua Softphone",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
    {
        s0: "Gọi trực tiếp qua Web & APP",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
    {
        s0: "Phiếu Ghi (Ticket)",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
    {
        s0: "Quản lý khách hàng",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
    {
        s0: "Quản lý nhân viên",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
    {
        s0: "Marketing – Chiến dịch",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
    {
        s0: "Cấu hình tổng đài",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
    {
        s0: "Phân quyền",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
    {
        s0: "Thống kê – báo cáo",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
    {
        s0: "Chăm sóc đa kênh (Facebook – Zalo OA)",
        s1: false,
        s2: true,
        s3: false,
        s4: true,
    },
    {
        s0: "Cấu hình tổng đài",
        s1: false,
        s2: true,
        s3: false,
        s4: true,
    },
    {
        s0: "Voice AI",
        s1: false,
        s2: false,
        s3: true,
        s4: true,
    },
    {
        s0: "Tích hợp nền tảng khác",
        s1: true,
        s2: true,
        s3: true,
        s4: true,
    },
];

export const data1 = [
    {
        s0: "< 10 User",
        s1: "400,000",
        s2: "500,000",
        s3: "Báo giá theo kịch bản",
    },
    {
        s0: "Từ 10 – 30 User",
        s1: "750,000",
        s2: "1,000,000",
        s3: "Báo giá theo kịch bản",
    },
    {
        s0: "30 – 50 User",
        s1: "1,000,000",
        s2: "1,500,000",
        s3: "Báo giá theo kịch bản",
    },
    {
        s0: "50 – 100 User",
        s1: "2,000,000",
        s2: "2,500,000",
        s3: "Báo giá theo kịch bản",
    },
    {
        s0: "> 100 User",
        s1: "2,500,000",
        s2: "3,000,000",
        s3: "Báo giá theo kịch bản",
    },
];
export const data2 = [
    {
        s0: "MẶC ĐỊNH",
        s1: null,
        s2: "<= 10 USERS",
        s3: "<= 30 USERS",
        s4: "<= 50 USERS",
        s5: "> 50 USERS",
    },
    {
        s0: "Số lượng ticket hỗ  trợ / tháng",
        s1: "Không giới hạn",
        s2: "Không giới hạn",
        s3: "Không giới hạn",
        s4: "Không giới hạn",
    },
    {
        s0: "Đào tạo sử dụng ( Online )",
        s1: "1",
        s2: "2",
        s3: "2",
        s4: "2",
    },
    {
        s0: "Hotline",
        s1: "có",
        s2: "có",
        s3: "có",
        s4: "có",
    },
    {
        s0: "",
        s1: "",
        s2: "",
        s3: "Có nhân sự hỗ trợ trực tiếp qua các group",
    },
    {
        s0: " MUA THÊM",
        s1: "Training Online",
        s2: "250,000 VNĐ  / buổi",
        s3: "",
        s4: "",
        s5: "",
    },
    {
        s0: "Training/ Support Onsite",
        s1: "500,000 VNĐ  / buổi",
        s2: "Số lượng tham gia tối đa 10 người",
    },
    {
        s0: "",
        s1: "1500,000 VNĐ  / buổi",
        s2: "Số lượng tham gia > 10 người",
        s3: null,
    },
];
